<?php
//----------------------------------------------------------------------//
//    TITLE: PHP Class for bottom                                       //
//    MAKER: SMStudio                                                   //
//    specially for SMS CMS (SM & Shurup Content Management System)     //
//----------------------------------------------------------------------//


$MDL_TITLE="Bottom";
$MDL_DESCR="For bottom";
$MDL_UNIQUEID="bottom";
$MDL_MAKER="SMStudio";


if(!$_GETINFO)
{


global $timer;
$timer->stop();
OUT("Page generated by: ".$timer->elapsed());
/////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////
?>
<?php
}
?>