<?php
$INDMDS[0]="news";
$INDMDS[1]="articles";
$INDMDS[2]="tenders";
$INDMDS[3]="annoucements";
$INDMDS[4]="pager";
$INDMDS[5]="guestbook";
$INDMDS[6]="smdsforum";
$INDMDS[7]="users";
$INDMDS[8]="smadbis";
?>