<?php
$vrs=array();
$file1=file("$file_forum_ini");
$file="";
foreach($file1 as $string)
	{
	$file.=$string;
	}
$vrs=explode("[}={]",$file);
for($i=0;$i<count($vrs);$i++)
	{
	$vrs[$i]=str_replace("\"","''",$vrs[$i]);
	}
$vars['login_len']=$vrs[0];
$vars['login_min']=$vrs[1];
$vars['pass_len']=$vrs[2];
$vars['pass_min']=$vrs[3];
$vars['nick_len']=$vrs[4];
$vars['nick_min']=$vrs[5];
$vars['email_len']=$vrs[6];
$vars['email_min']=$vrs[7];
$vars['url_len']=$vrs[8];
$vars['url_min']=$vrs[9];
$vars['city_len']=$vrs[10];
$vars['city_min']=$vrs[11];
$vars['sign_len']=$vrs[12];
$vars['sign_min']=$vrs[13];
$vars['info_len']=$vrs[14];
$vars['info_min']=$vrs[15];
$vars['title_len']=$vrs[16];
$vars['title_min']=$vrs[17];
$vars['desc_len']=$vrs[18];
$vars['desc_min']=$vrs[19];
$vars['mes_len']=$vrs[20];
$vars['mes_min']=$vrs[21];
$vars['your_email']=$vrs[22];
$vars['your_name']=$vrs[23];
$vars['forum_addr']=$vrs[24];
$vars['forum_name']=$vrs[25];
$vars['time_zone']=$vrs[26];
$vars['kvo']=$vrs[27];
$vars['time_exit']=$vrs[28];
$vars['show_users']=$vrs[29];
$vars['show_online']=$vrs[30];
$vars['log_index']=$vrs[31];
$vars['log_auth']=$vrs[32];
//

$vars['mat_filter_word']=$vrs[33];
$usr_view['nick']=$vrs[34];
$usr_view['avatar']=$vrs[35];
$usr_view['city']=$vrs[36];
$usr_view['email']=$vrs[37];
$usr_view['url']=$vrs[38];
$usr_view['sex']=$vrs[39];
$usr_view['sign']=$vrs[40];
$usr_view['rang']=$vrs[41];
$usr_view['count']=$vrs[42];
$usr_view['raiting']=$vrs[43];
$vars['avatar_maxwidth']=$vrs[44];
$vars['avatar_maxheight']=$vrs[45];
$vars['avatar_maxsize']=$vrs[46];
$vars['theme_ext']=$vrs[47];
$vars['mess_ext']=$vrs[48];
$vars['voting_ext']=$vrs[49];

$levels[0]=$vrs[50];
$levels[1]=$vrs[51];
$levels[2]=$vrs[52];
$levels[3]=$vrs[53];
$levels[4]=$vrs[54];
$levels[5]=$vrs[55];
$levels[6]=$vrs[56];
$levels[7]=$vrs[57];
$vars['guest_rights']=$vrs[58];
$vars['reg_rights']=$vrs[59];
$smb=$vrs[60];
$smb1=$vrs[61];
$table_all=$vrs[62];
$td_all=$vrs[63];
$table_messages=$vrs[64];
$td_messages=$vrs[65];
$td_userinfo=$vrs[66];
$vars['show_rights']=$vrs[67];
$vars['show_statistic']=$vrs[68];
$vars['show_info_banner']=$vrs[69];
$vars['__contents']=$vrs[70];
$vars['show_owner']=$vrs[71];
$vars['subj_len']=$vrs[72];
$vars['subj_min']=$vrs[73];
$vars['pmes_len']=$vrs[74];
$vars['pmes_min']=$vrs[75];
$vars['show_newpm']=$vrs[76];
$vars['t_kvo']=$vrs[77];
$vars['show_thhp']=$vrs[78];
$vars['show_view_t']=$vrs[79];
$vars['make_chmod']=$vrs[80];
$vars['show_gentime']=$vrs[81];
$vars['word_len']=$vrs[82];
$vars['smls_count']=$vrs[83];
$vars['language']=$vrs[84];
$vars['downl_enable']=$vrs[85];
$vars['file_maxsize']=$vrs[86];
$vars['file_maxdesc']=$vrs[87];
$vars['file_maxlen']=$vrs[88];
$vars['mat_filter']=$vrs[89];
$vars['pers_color']=$vrs[90];

include "$file_directories";

$i=1;
	while(file_exists($vars['dir_smiles']."/sml0".$i.".gif")==true)
		{
		$smiles[$i]['img']="sml0$i.gif";
		$smiles[$i]['code']="[SML0$i]";
		$i++;
		}
	while(file_exists($vars['dir_smiles']."/sml".$i.".gif")==true)
		{
		$smiles[$i]['img']="sml$i.gif";
		$smiles[$i]['code']="[SML$i]";
		$i++;
		}
$vars['smiles_count']=$i-1;

$rangs1=array();
$file1=file($vars['file_rangs']);
$file="";
foreach($file1 as $string)
	{
	$file.=$string;
	}
$rangs1=explode("$smb",$file);
$j=0;
for($i=0;$i<count($rangs1);$i=$i+2)
	{
	$rangs[$j]['rang']=$rangs1[$i];
	$rangs[$j]['count']=$rangs1[$i+1];
	$j++;
	}
$vars['rangs_count']=$j;



$hz=1;
?>
