replace into url_categories(cid,title) values ("58","Abortion");
replace into url_categories(cid,title) values ("40","Alcohol");
replace into url_categories(cid,title) values ("38","Anonymous Proxies");
replace into url_categories(cid,title) values ("23","Art / Museums / Memorials / Monuments");
replace into url_categories(cid,title) values ("5","Auctions / Classified Ads");
replace into url_categories(cid,title) values ("54","Banking / Home Banking");
replace into url_categories(cid,title) values ("48","Building / Residence / Architecture / Furniture");
replace into url_categories(cid,title) values ("29","Chat");
replace into url_categories(cid,title) values ("21","Cinema / Television");
replace into url_categories(cid,title) values ("8","Cities / Regions / Countries");
replace into url_categories(cid,title) values ("35","Communication Services");
replace into url_categories(cid,title) values ("14","Computer Crime");
replace into url_categories(cid,title) values ("19","Computer Games");
replace into url_categories(cid,title) values ("43","Dating / Relationships");
replace into url_categories(cid,title) values ("32","Digital Postcards");
replace into url_categories(cid,title) values ("9","Education");
replace into url_categories(cid,title) values ("2","Erotic / Sex");
replace into url_categories(cid,title) values ("46","Fashion / Cosmetics / Jewelry");
replace into url_categories(cid,title) values ("53","Financial Services / Investment / Insurance");
replace into url_categories(cid,title) values ("18","Gambling / Lottery");
replace into url_categories(cid,title) values ("27","General News / Newspapers / Magazines");
replace into url_categories(cid,title) values ("6","Governmental Organizations");
replace into url_categories(cid,title) values ("57","Health");
replace into url_categories(cid,title) values ("26","Humor / Comics");
replace into url_categories(cid,title) values ("13","Illegal Activities");
replace into url_categories(cid,title) values ("39","Illegal Drugs");
replace into url_categories(cid,title) values ("63","Instant Messaging");
replace into url_categories(cid,title) values ("52","Investment Brokers / Stocks");
replace into url_categories(cid,title) values ("36","IT Security / IT Information");
replace into url_categories(cid,title) values ("51","Job Search");
replace into url_categories(cid,title) values ("25","Literature / Books");
replace into url_categories(cid,title) values ("61","Malware");
replace into url_categories(cid,title) values ("31","Mobile Telephony");
replace into url_categories(cid,title) values ("24","Music");
replace into url_categories(cid,title) values ("49","Nature / Environment / Animals");
replace into url_categories(cid,title) values ("30","Newsgroups / Bulletin Boards / Blogs");
replace into url_categories(cid,title) values ("7","Non-Governmental Organizations");
replace into url_categories(cid,title) values ("50","Personal Homepages");
replace into url_categories(cid,title) values ("15","Political Extreme / Hate / Discrimination");
replace into url_categories(cid,title) values ("10","Political Parties");
replace into url_categories(cid,title) values ("1","Pornography");
replace into url_categories(cid,title) values ("22","Recreational Facilities / Amusement / Theme Parks");
replace into url_categories(cid,title) values ("11","Religion");
replace into url_categories(cid,title) values ("44","Restaurants / Bars");
replace into url_categories(cid,title) values ("33","Search Engines / Web Catalogs / Portals");
replace into url_categories(cid,title) values ("12","Sects");
replace into url_categories(cid,title) values ("42","Self-Help / Addiction");
replace into url_categories(cid,title) values ("4","Shopping");
replace into url_categories(cid,title) values ("34","Software / Hardware / Distributors");
replace into url_categories(cid,title) values ("47","Sports");
replace into url_categories(cid,title) values ("3","Swimwear / Lingerie");
replace into url_categories(cid,title) values ("41","Tobacco");
replace into url_categories(cid,title) values ("20","Toys");
replace into url_categories(cid,title) values ("45","Travel");
replace into url_categories(cid,title) values ("55","Vehicles / Transportation");
replace into url_categories(cid,title) values ("17","Violence / Extreme");
replace into url_categories(cid,title) values ("16","Warez / Hacking / Illegal Software");
replace into url_categories(cid,title) values ("56","Weapons / Military");
replace into url_categories(cid,title) values ("28","Web Mail");
replace into url_categories(cid,title) values ("37","Website Translation");