<?
if(isset($_SESSION['graph_prev_values']))
	unset($_SESSION['graph_prev_values']);
if(isset($_SESSION['graph_prev_indexes']))
	unset($_SESSION['graph_prev_indexes']);
if(isset($_SESSION['graph_mem_values']))
	unset($_SESSION['graph_mem_values']);
if(isset($_SESSION['graph_mem_indexes']))
	unset($_SESSION['graph_mem_indexes']);
