<?php
$DIRS["tnds_list_cur"]="data/tenders/list_cur";
$DIRS["tnds_list_pub"]="data/tenders/list_pub";
$DIRS["tnds_list_old"]="data/tenders/list_old";
$DIRS["tnds_down"]="downloads/tenders";
$DIRS["tnds_types"]="data/tenders/types.php";
$TND_ALLOW_UPLTYPES[0]=".doc";
$TND_ALLOW_UPLTYPES[1]=".rar";
$TND_ALLOW_UPLTYPES[2]=".zip";
$TND_MAX_ALLOW_UPLSIZE=5*1024*1024;
$TND_MAX_UPLFILES_COUNT=10;
?>