<?php
//AUTO-GENERATED CONFIG FILE FOR MODULE USERS
$DIRS["users_list"]="data/users/list.php";
$DIRS["users_groups"]="data/users/groups.php";
$DIRS["users_data"]="data/users/data";
$DIRS["users_private"]="data/users/private";
$DIRS["users_avatars"]="img/avatars";
$DIRS["users_online"]="data/users/online.php";
$GV_USERS["max_av_size"]=50;
$GV_USERS["max_av_width"]=150;
$GV_USERS["max_av_height"]=150;
$GV_USERS["max_login_len"]=30;
$GV_USERS["max_passwd_len"]=30;
$GV_USERS["max_info_len"]=2500;
$GV_USERS["max_sign_len"]=300;
$GV_USERS["max_nick_len"]=30;
$GV_USERS["max_email_len"]=30;
$GV_USERS["max_url_len"]=30;
$GV_USERS["max_icq_len"]=30;
$GV_USERS["max_city_len"]=30;
$GV_USERS["max_country_len"]=30;
$GV_USERS["min_login_len"]="2";
$GV_USERS["min_password_len"]="3";
$GV_USERS["min_nick_len"]="2";
$GV_USERS["start_level"]=1;
$GV_USERS["start_group"]="users";
?>