<?php
$language['welcome']="Добро пожаловать, ";
$language['hello_guest']="!";
$language['hello_user']="!";
$language['hello_admin']="! Вы можете администрировать этот форум!";
$language['nr_private']="У вас ";
$language['nr_private1']=" приватных сообщений, и";
$language['nr_private2']=" из них не прочитано!</font>";
$language['forbidden_n']="<CENTER><B>ПРОСТИТЕ, НО ВЫ НЕ МОЖЕТЕ ПРОСМАТРИВАТЬ ЭТУ СТРАНИЦУ С ПРАВАМИ НИЖЕ ";
$language['forbidden_7']="<CENTER><B>ПРОСТИТЕ, НО ВЫ НЕ МОЖЕТЕ ПРОСМАТРИВАТЬ ЭТУ СТРАНИЦУ С ПРАВАМИ НИЖЕ 7!";
$language['title_topview']="<CENTER><b>Просмотр тем</b></CENTER>";
$language['title_private']="<CENTER><b>Приватные сообщения</b></CENTER>";
$language['title_addtopic']="<CENTER><b>Добавить тему</b></CENTER>";
$language['title_addmessage']="<CENTER><b>Добавить сообщение</b></CENTER>";
$language['title_register']="<CENTER><b>Регистрация</b></CENTER>";
$language['title_authorize']="<CENTER><b>Авторизация</b></CENTER>";
$language['title_mesedit']="<CENTER><b>Редактор сообщений</b></CENTER>";
$language['title_addvoting']="<CENTER><b>Добавить голосование</b></CENTER>";
$language['title_userinfo']="<CENTER><b>Информация</b></CENTER>";
$language['title_find']="<CENTER><b>Поиск по сообщениям</b></CENTER>";
$language['title_mesdelete']="<CENTER><b>Удаление сообщения</b></CENTER>";
$language['title_topdelete']="<CENTER><b>Удаление темы</b></CENTER>";
$language['title_topedit']="<CENTER><b>Редактор темы</b></CENTER>";
$language['back_topindex']="<center><br><a href=?p=$p&forum_ext=$forum_ext>НА ГЛАВНУЮ</a><br></center>";
$language['title_profile']="<CENTER><b>Профиль</b></CENTER>";
$language['owner']="<br><CENTER><SMALL>Правом на владение этим форумом обладает:".$vars['your_name']."</SMALL></CENTER>";
$language['gentime']="<center><SMALL>Страница сгенерирована за: ";
$language['sec']="сек";
$language['quote_man']="писал(а):";
$language['quote']="цитата:";

$language['but_index']="<a href=\"?p=$p&forum_ext=$forum_ext&t_page=$t_page\">ТЕМЫ</a>";
$language['but_newtopic']="<a href=\"?p=$p&forum_ext=$forum_ext&id=add_topic\">НОВАЯ ТЕМА</a>";
$language['but_register']="<a href=\"?p=$p&id=register\">РЕГИСТРАЦИЯ</a>";
$language['but_auth']="<a href=\"?p=$p&id=auth\">АВТОРИЗАЦИЯ</a>";
$language['but_profile']="<a href=\"?p=$p&forum_ext=$forum_ext&id=profile\">ПРОФИЛЬ</a>";
$language['but_private']="<a href=\"?p=$p&forum_ext=$forum_ext&id=pers_messages\">ПРИВАТ</a>";
$language['but_admin']="<a href=\"?p=$p&forum_ext=$forum_ext&id=admin\">АДМИН</a>";
$language['but_exit']="<a href=\"?p=$p&id=exit\">ВЫХОД</a>";
$language['but_faq']="<a href=\"?p=$p&forum_ext=$forum_ext&id=faq\">FAQ</a>";

$language['showall'][0]="Название Темы:";
$language['showall'][1]="Автор:";
$language['showall'][2]="Дата создания:";
$language['showall'][3]="Последний ответ:";
$language['showall'][4]="Просмотров:";
$language['showall'][5]="Сообщений:";
$language['showall'][6]="Описание темы:";
$language['showall'][7]="Просмотр:";
$language['showall'][8]="СООБЩЕНИЙ НЕТ!";

$language['stat_totalusers']="Всего зарегистрировано:";
$language['stat_totalmessages']="Всего сообщений в разделе:";
$language['stat_largestwrite']="Больше всех написал:";
$language['stat_largesttopics']="Больше всего тем создал:";
$language['stat_largestraiting']="Самый большой рейтинг у";

$language['online_total']="Всего он-лайн:";
$language['online_guests']="Гостей:";
$language['online_registered']="Зарегистрированных:";
$language['online_whois']="Кто он-лайн:";

$language['error403']="ОШИБКА 403! Вы не имеете права просматривать данную страницу...";

$language['topics_total']="Всего тем:";
$language['topics_showed']="Показано:";
$language['topics_from']="с";
$language['topics_to']="по";
$language['topics_all']="все";

$language['ip_blocked']="ПРОСТИТЕ,  НО ВАМ ЗАПРЕЩЕНО ПОСЕЩАТЬ ДАННУЮ СТРАНИЦУ!";

$language['userinfo_nick']="Ник:";
$language['userinfo_date']="Дата регистрации:";
$language['userinfo_rang']="Ранг:";
$language['userinfo_count']="Сообщений:";
$language['userinfo_topics']="Создано тем:";
$language['userinfo_raiting']="Рейтинг:";
$language['userinfo_sex']="Пол:";
$language['userinfo_city']="Местонахождение:";
$language['userinfo_email']="E-mail:";
$language['userinfo_url']="URL:";
$language['userinfo_sign']="Подпись:";
$language['userinfo_info']="Доп. информация:";

$language['topic_delete_cant']="Нельзя удалить эту тему! Сначала удалите все записи!<a href=\"?p=$p&forum_ext=$forum_ext&id=showtopic&topic=$topic&page=$page\">НАЗАД</a>";
$language['topic_delete_success']="Тема успешно удалена! <a href=\"?p=$p&forum_ext=$forum_ext\">ПОСМОТРЕТЬ</a>";
$language['topic_delete_confirm']="Вы действительно хотите удалить тему";
$language['topic_delete_author']="Автор:";
$language['topic_delete_email']="E-mail:";
$language['topic_delete_url']="URL:";
$language['topic_delete_delbut']="Удалить!";

$language['register_login']="Логин:";
$language['register_nick']="Ник:";
$language['register_password']="Пароль:";
$language['register_city']="Откуда:";
$language['register_email']="E-mail:";
$language['register_url']="URL:";
$language['register_sex']="Пол:";
$language['register_sign']="Подпись:";
$language['register_info']="Доп. информация:";
$language['register_butreg']="Зарегистрироваться";
$language['sex_man']="мужской";
$language['sex_woman']="женский";


$language['auth_log_try']="пытался авторизоваться";
$language['auth_log_login']="введя логин";
$language['auth_log_password']="и пароль";
$language['auth_log_failed']="но не удалось...";
$language['auth_log_success']="и получилось!";
$language['auth_incorrect']="Неверная комбинация логин-пароль! <a href=?p=$p&forum_ext=$forum_ext&id=auth>Попробовать ещё раз</a>";
$language['auth_login']="Логин:";
$language['auth_password']="Пароль:";
$language['auth_rememberme']="Запомнить меня";
$language['auth_enter']="ВОЙТИ";

$language['delete_success']="Сообщение успешно удалено!!<a href=\"?p=$p&forum_ext=$forum_ext&id=showtopic&topic=$topic&page=$page\">ПОСМОТРЕТЬ</a>";
$language['delete_confirm']="Вы действительно хотите удалить сообщение:";
$language['delete_date']="Дата:";
$language['delete_nick']="Ник:";
$language['delete_email']="E-mail:";
$language['delete_url']="URL:";
$language['delete_message']="Сообщение:";
$language['delete_delete']="Удалить!";
$language['delete_back']="НАЗАД";

$language['addvoting_success']="Голосование успешно добавлено!";
$language['addvoting_back']="НАЗАД";
$language['addvoting_addvoting']="Добавить голосование в тему:";
$language['addvoting_question']="Заголовок опроса(вопрос)";
$language['addvoting_variantn']="Вариант ответа №";
$language['addvoting_activate']="Активировать голосование";
$language['addvoting_variant']="вариант";

$language['smiles_selectfirst']="Надо сначала выделить фрагмент текста!";
$language['smiles_entername']="Введите имя того, кого хотите цитировать:";
$language['smiles_center']="Центр";
$language['smiles_underline']="Подчерк";
$language['smiles_bold']="Жирно";
$language['smiles_italic']="Курсив";
$language['smiles_quote']="Цитата";
$language['smiles_image']="Картинка";
$language['smiles_quoteman']="Цит. чел.";
$language['smiles_jsoff1']="Для вашего браузера";
$language['smiles_jsoff2']="JavaScript отключён...";
$language['smiles_tagsinfo']="
Для настройки сообщения используйте следующие теги:<br>
Центрирование: [CENTER]текст[/CENTER]<br>
Подчёркивание:[U]текст[/U]<br>
Жирно:[B]текст[/B]<br>
Курсив[I]текст[/I]<br>
Цитата:[QUOTE]текст[/QUOTE]<br>
Картинка[IMG]URL картинки[/IMG]<br>
Цитата ника:[QUOTE=nick=QUOTE]текст[/QUOTE]<br>
Выделение цветом:[COLOR=color]текст[/COLOR]";
$language['smiles_writenext']="Чтобы использовать смайлы пишите следующее:";
$language['smiles_moresmiles']="Ещё смайлы";

$language['showtopic_viewtopic']="Просмотр темы";
$language['showtopic_author']="Автор:";
$language['showtopic_email']="E-mail:";
$language['showtopic_url']="URL:";
$language['showtopic_deletetopic']="Удалить тему";
$language['showtopic_addvoting']="Добавить в тему голосование";
$language['showtopic_deletevoting']="Удалить из темы голосование";
$language['showtopic_edit']="Редактировать данные темы";
$language['showtopic_page']="страница:";
$language['showtopic_total']="Всего записей:";
$language['showtopic_showedfrom']="Показано с";
$language['showtopic_to']="по";
$language['showtopic_allshowed']="Показаны все.";
$language['showtopic_showall']="Показать все";
$language['showtopic_showpage']="Показать постранично";

$language['months']=array("января","февраля","марта","апреля","мая","июня","июля","августа","сентября","октября","ноября","декабря");
$language['weekdays']=array(0=>"Воскресенье",1=>"Понедельник",2=>"Вторник",3=>"Среда",4=>"Четверг",5=>"Пятница",6=>"Суббота");

$language['addtopic_titlemin']="Длина названия темы должна быть не менее";
$language['addtopic_nickmin']="Длина ника должна быть не менее";
$language['addtopic_emailmin']="Длина e-mail'а должна быть не менее";
$language['addtopic_urlmin']="Длина URL должна быть не менее";
$language['addtopic_descrmin']="Длина описания должна быть не менее";
$language['addtopic_nickforb']="Чтобы использовать данный ник, вам нужно авторизоваться!!";
$language['addtopic_symbols']="символов!";


$language['admin_menu01']="Редактор основных переменных";
$language['admin_menu02']="Редактор смайлов";
$language['admin_menu03']="Переменные TRUE и FALSE";
$language['admin_menu04']="Настройка званий";
$language['admin_menu05']="Уровни доступа к форуму";
$language['admin_menu06']="Блокировка по IP- адресам";
$language['admin_menu07']="Просмотр логов index";
$language['admin_menu08']="Просмотр логов авторизации";
$language['admin_menu09']="Расширения, директории и файлы";
$language['admin_menu10']="Прочие настройки";
$language['admin_menu11']="Настройка запрещённых слов";

$language['admin_vars01_01']="РЕДАКТОР ЮЗЕРОВ:";
$language['admin_vars01_02']="USER ID:";
$language['admin_vars01_03']="Удалить юзера";
$language['admin_vars01_04']="Аватара:";
$language['admin_vars01_05']="Логин:";
$language['admin_vars01_06']="Пароль:";
$language['admin_vars01_07']="Ник:";
$language['admin_vars01_08']="Местонахождение:";
$language['admin_vars01_09']="Пол:";
$language['admin_vars01_10']="E-mail:";
$language['admin_vars01_11']="URL:";
$language['admin_vars01_12']="Дата регистрации:";
$language['admin_vars01_13']="Ранг:";
$language['admin_vars01_14']="Сообщений:";
$language['admin_vars01_15']="+/- рейтинг:";
$language['admin_vars01_16']="Права:";
$language['admin_vars01_17']="Подпись:";
$language['admin_vars01_18']="Доп. информация:";
$language['admin_vars01_19']="Изменить";
$language['admin_vars01_20']="Редактировать";
$language['admin_goto']="Перейти";
$language['admin_back']="назад";


$language['admin_vars02_01']="УДАЛЕНИЕ ЮЗЕРА:";
$language['admin_vars02_02']="Вы уверены, что хотите удалить юзера:";
$language['admin_vars02_03']="ДА!";
$language['admin_vars02_04']="НЕТ!";
$language['admin_vars02_05']="Юзер удалён успешно!";
$language['admin_vars02_06']="Данные изменены!";
$language['admin_vars02_07']="При удалении произошла ошибка!";

$language['admin_vars01'][0]="РЕДАКТОР ОСНОВНЫХ ПЕРЕМЕННЫХ:";
$language['admin_vars01'][1]="Настройки форума:";
$language['admin_vars01'][2]="Ваш E-mail:";
$language['admin_vars01'][3]="Ваше имя:";
$language['admin_vars01'][4]="Адрес форума:";
$language['admin_vars01'][5]="Название форума:";
$language['admin_vars01'][6]="Ограничения по длине:";
$language['admin_vars01'][7]="Логин: (MAX)";
$language['admin_vars01'][8]="Логин: (MIN)";
$language['admin_vars01'][9]="Пароль: (MAX)";
$language['admin_vars01'][10]="Пароль: (MIN)";
$language['admin_vars01'][11]="Ник: (MAX)";
$language['admin_vars01'][12]="Ник: (MIN)";
$language['admin_vars01'][13]="URL: (MAX)";
$language['admin_vars01'][14]="URL: (MIN)";
$language['admin_vars01'][15]="Местоположение: (MAX)";
$language['admin_vars01'][16]="Местоположение: (MIN)";
$language['admin_vars01'][17]="Подпись: (MAX)";
$language['admin_vars01'][18]="Подпись: (MIN)";
$language['admin_vars01'][19]="Доп. инфо: (MAX)";
$language['admin_vars01'][20]="Доп. инфо: (MIN)";
$language['admin_vars01'][21]="Заголовок темы: (MAX)";
$language['admin_vars01'][22]="Заголовок темы: (MIN)";
$language['admin_vars01'][23]="Описание темы: (MAX)";
$language['admin_vars01'][24]="Описание темы: (MIN)";
$language['admin_vars01'][25]="Сообщение: (MAX)";
$language['admin_vars01'][26]="Сообщение: (MIN)";
$language['admin_vars01'][27]="Тема приватного письма: (MAX)";
$language['admin_vars01'][28]="Тема приватного письма: (MIN)";
$language['admin_vars01'][29]="Сообщение привата: (MAX)";
$language['admin_vars01'][30]="Сообщение привата: (MIN)";
$language['admin_vars01'][31]="Длина слова в сообщениях: (MAX)";
$language['admin_vars01'][32]="Выводить первые N смайлов:";
$language['admin_vars01'][33]="Другие:";
$language['admin_vars01'][34]="Временная зона(Гринвич+к-во сек.):";
$language['admin_vars01'][35]="Ширина аватары (пкс):";
$language['admin_vars01'][36]="Высота аватары (пкс):";
$language['admin_vars01'][37]="Объём аватары (Кб):";
$language['admin_vars01'][38]="Кол-во ответов на страницу:";
$language['admin_vars01'][39]="Кол-во тем на страницу:";
$language['admin_vars01'][40]="На что заменять мат:";
$language['admin_vars01'][41]="Активность (время отклика) (сек):";
$language['admin_vars01'][42]="Изменить";
$language['admin_vars01'][43]="Переменные изменены!";
$language['admin_vars01'][44]="E-mail: (MAX)";
$language['admin_vars01'][45]="E-mail: (MIN)";
$language['admin_vars01'][46]="Язык";
$language['admin_vars01'][47]="все";

$language['admin_vars02'][0]="РЕДАКТОР СМАЙЛОВ:";
$language['admin_vars02'][1]="Не удалось удалить файл:";

$language['admin_vars02'][3]="Файл";
$language['admin_vars02'][4]="успешно удалён...";
$language['admin_vars02'][5]="ВЫ ДЕЙСТВИТЕЛЬНО ХОТИТЕ УДАЛИТЬ ВСЕ СМАЙЛЫ??";
$language['admin_vars02'][6]="ДА, Я УВЕРЕН!";
$language['admin_vars02'][7]="ошибка удаления!";
$language['admin_vars02'][8]="ГОТОВО!";
$language['admin_vars02'][9]="успешно закачан!";
$language['admin_vars02'][10]="ОШИБКА ЗАГРУЗКИ";
$language['admin_vars02'][11]="СМАЙЛОВ НЕТ!";
$language['admin_vars02'][12]="удалить";
$language['admin_vars02'][13]="удалить ВСЕ смайлы";
$language['admin_vars02'][14]="Закачать!";
$language['admin_vars02'][15]="Если смайлы не обновляются после удаления или загрузки - очистите кэш браузера (в IE CTRL+F5)";
$language['admin_vars02'][16]="Показать N форм загрузки:";
$language['admin_vars02'][17]="Показать";


$language['admin_vars03'][0]="РЕДАКТОР TRUE-FALSE ПЕРЕМЕННЫХ:";
$language['admin_vars03'][1]="Показывать слева от сообщений:";
$language['admin_vars03'][2]="Ник:";
$language['admin_vars03'][3]="Аватару:";
$language['admin_vars03'][4]="Местоположение:";
$language['admin_vars03'][5]="E-mail:";
$language['admin_vars03'][6]="URL:";
$language['admin_vars03'][7]="Пол:";
$language['admin_vars03'][8]="Подпись(под сообщением):";
$language['admin_vars03'][9]="Ранг:";
$language['admin_vars03'][10]="К-во сообщений:";
$language['admin_vars03'][11]="Рейтинг:";
$language['admin_vars03'][12]="При показе тем показывать:";
$language['admin_vars03'][13]="Ссылки на темы с более высокими правами:";
$language['admin_vars03'][14]="Возможность просмотра темы:";
$language['admin_vars03'][15]="Показ внизу форума:";
$language['admin_vars03'][16]="Юзеров(к-во гостей, зарег-ных...):";
$language['admin_vars03'][17]="Тех, кто он-лайн:";
$language['admin_vars03'][18]="Статистику:";
$language['admin_vars03'][19]="Инфо-баннер:";
$language['admin_vars03'][20]="Владельца форума:";
$language['admin_vars03'][21]="Оповещать о новых сообщениях привата:";
$language['admin_vars03'][22]="Время генерации страницы:";
$language['admin_vars03'][23]="Права:";
$language['admin_vars03'][24]="Прочее:";
$language['admin_vars03'][25]="Вести логи входа на главную?:";
$language['admin_vars03'][26]="Вести логи авторизации?:";
$language['admin_vars03'][27]="Делать CHMOD на DATA-директорию?:";
$language['admin_vars03'][28]="Фильтр мата:";
$language['admin_vars03'][29]="Переменные изменены!";
$language['admin_vars03'][30]="да";
$language['admin_vars03'][31]="нет";
$language['admin_vars03'][32]="вкл";
$language['admin_vars03'][33]="выкл";

$language['admin_vars04'][0]="РЕДАКТОР РАНГОВ:";
$language['admin_vars04'][1]="Ранг<td>Сообщений";
$language['admin_vars04'][2]="Переменные изменены!";
$language['admin_vars04'][3]="РЕДАКТОР УРОВНЕЙ ДОСТУПА:";
$language['admin_vars04'][4]="Названия уровней прав доступа к форуму:";
$language['admin_vars04'][5]="-й уровень:";
$language['admin_vars04'][6]="7-й уровень:";
$language['admin_vars04'][7]="Юзеры изначально на следующем уровне:";
$language['admin_vars04'][8]="Уровень прав гостей:";
$language['admin_vars04'][9]="Зарегистрировавшись юзер получает уровень:";
$language['admin_vars04'][10]="БЛОКИРОВКА ПО IP-АДРЕСАМ:";

$language['admin_vars05'][0]="РЕДАКТОР ПУТЕЙ И РАСШИРЕНИЙ:";
$language['admin_vars05'][1]="<b><font color=red>ВНИМАНИЕ!</font></b> Если вы не знаете что означают эти переменные, лучше ничего не меняйте!";
$language['admin_vars05'][2]="Пути:";
$language['admin_vars05'][3]="Папка с юзерами:";
$language['admin_vars05'][4]="Папка с темами:";
$language['admin_vars05'][5]="Папка с опросами:";
$language['admin_vars05'][6]="Папка с аватарами:";
$language['admin_vars05'][7]="Папка со смайлами:";
$language['admin_vars05'][8]="Файл юзеры он-лайн:";
$language['admin_vars05'][9]="Файл с рангами:";
$language['admin_vars05'][10]="Файл с логами:";
$language['admin_vars05'][11]="Файл с логами авторизации:";
$language['admin_vars05'][12]="Файл с запрещёнными словами:";
$language['admin_vars05'][13]="Файл с заблокированными IP:";
$language['admin_vars05'][14]="Расширения:";
$language['admin_vars05'][15]="Файл с темой:";
$language['admin_vars05'][16]="Файл с сообщениями:";
$language['admin_vars05'][17]="Файл с голосованием:";
$language['admin_vars05'][18]="РЕДАКТОР ПРОЧИХ ПЕРЕМЕННЫХ:";
$language['admin_vars05'][19]="<b><font color=red>ВНИМАНИЕ!</font></b> Если вы не знаете что означают эти переменные, лучше ничего не меняйте!";
$language['admin_vars05'][20]="Спец-символы:";
$language['admin_vars05'][21]="1-й уровень:";
$language['admin_vars05'][22]="2-й уровень:";
$language['admin_vars05'][23]="<b><font color=red>ВНИМАНИЕ!</font></b> Если вы не очень хорошо знаете html, ни в коем случае не меняйте след. переменные!";
$language['admin_vars05'][24]="Коды таблиц:";
$language['admin_vars05'][25]="Основная таблица:";
$language['admin_vars05'][26]="Ячейка осн. таблицы:";
$language['admin_vars05'][27]="Таблица показа сообщений:";
$language['admin_vars05'][28]="Ячейка показа сообщений:";
$language['admin_vars05'][29]="Ячейка слева от сообщений:";

$language['admin_vars06'][0]="ПРОСМОТР ЛОГОВ ОБРАЩЕНИЯ К ГЛАВНОЙ СТРАНИЦЕ (СПИСОК ТЕМ):";
$language['admin_vars06'][1]="Архив логов адреса";
$language['admin_vars06'][2]="Последний заход:";
$language['admin_vars06'][3]="Пришёл через порт:";
$language['admin_vars06'][4]="из:";
$language['admin_vars06'][5]="Данные о броузере:";
$language['admin_vars06'][6]="Тип соединения:";
$language['admin_vars06'][7]="Удалить логи этого IP";
$language['admin_vars06'][8]="ЛОГ УДАЛЁН!";
$language['admin_vars06'][9]="ЛОГИ ОЧИЩЕНЫ!";
$language['admin_vars06'][10]="Вы уверены, что хотите ПОЛНОСТЬЮ очистить лог-файл?";
$language['admin_vars06'][11]="Лог адреса";
$language['admin_vars06'][12]="Последний заход:";
$language['admin_vars06'][13]="Данные о броузере:";
$language['admin_vars06'][14]="Архив логов этого IP";
$language['admin_vars06'][15]="Удалить логи этого IP";
$language['admin_vars06'][16]="ЛОГОВ НЕТ!";
$language['admin_vars06'][17]="Удалить все логи!";
$language['admin_vars06'][18]="ПРОСМОТР ЛОГОВ АВТОРИЗАЦИИ:";
$language['admin_vars06'][19]="Очистить";

$language['admin_vars07'][0]="Редактор запрещённых слов:";
$language['admin_vars07'][1]="+ СЛОВО";
$language['admin_vars07'][2]="- СЛОВО";
$language['admin_vars07'][3]="Сделать N слов:";
$language['admin_vars07'][4]="Перейти";
$language['admin_vars07'][5]="Переменные изменены!";

$language['admin_title']="ЗОНА АДМИНИСТРАТОРА";
$language['admin_title_usr']="Редактор юзеров:";

$language['persmes'][0]="Длина темы должна быть не менее";
$language['persmes'][1]="Длина сообщения должна быть не менее";
$language['persmes'][2]="Длина слов в сообщении должна быть не более";
$language['persmes'][3]="Данный логин не зарегистрирован!!!!";
$language['persmes'][4]="не прочитано";
$language['persmes'][5]="прочитано";
$language['persmes'][6]="Чтение приватного сообщения:";
$language['persmes'][7]="От";
$language['persmes'][8]="Информация";
$language['persmes'][9]="пол:";
$language['persmes'][10]="Сообщений:";
$language['persmes'][11]="Рейтинг:";
$language['persmes'][12]="удалить сообщение";
$language['persmes'][13]="назад";
$language['persmes'][14]="Вы уверены, что хотите удалить все сообщения?";
$language['persmes'][15]="УДАЛИТЬ ВСЕ СООБЩЕНИЯ!";
$language['persmes'][16]="Вы уверены, что хотите удалить сообщение";
$language['persmes'][17]="УДАЛИТЬ!";
$language['persmes'][18]="От:";
$language['persmes'][19]="Тема:";
$language['persmes'][20]="Дата:";
$language['persmes'][21]="Статус:";
$language['persmes'][22]="Действия:";
$language['persmes'][23]="НЕТ СООБЩЕНИЙ";
$language['persmes'][24]="Ответить на сообщение:";
$language['persmes'][25]="Написать новое приватное сообщение:";
$language['persmes'][26]="Кому:";
$language['persmes'][27]="Тема:";
$language['persmes'][28]="Сообщение:";
$language['persmes'][29]="Отправить";
$language['persmes'][30]="символов";
$language['persmes'][31]="Ошибка заполнения формы!";
$language['persmes'][32]="Сообщение успешно отправлено!";
$language['persmes'][33]="СДЕЛАНО!";

$language['addvoting'][0]="Голосование удалено успешно";
$language['addvoting'][1]="Вы действительно хотите удалить голосование из темы";
$language['addvoting'][2]="ДА! Я УВЕРЕН!";
$language['addvoting'][3]="НАЗАД";
$language['addvoting'][4]="Голосовать";

$language['showmes'][0]="Редактировать";
$language['showmes'][1]="Удалить";
$language['showmes'][2]="Информация";
$language['showmes'][3]="пол:";
$language['showmes'][4]="Сообщений:";
$language['showmes'][5]="Рейтинг:";

$language['addmes'][0]="Длина ника должна быть не менее";
$language['addmes'][1]="Длина e-mail'а должна быть не менее";
$language['addmes'][2]="Длина URL должна быть не менее";
$language['addmes'][3]="Длина сообщения должна быть не менее";
$language['addmes'][4]="Длина слов в сообщении должна быть не более";
$language['addmes'][5]="символов";
$language['addmes'][6]="Чтобы использовать данный ник, вам нужно авторизоваться!!";
$language['addmes'][7]="Ошибка заполнения формы! ";
$language['addmes'][8]="Тема:";
$language['addmes'][9]="Ник:";
$language['addmes'][10]="E-mail:";
$language['addmes'][11]="URL:";
$language['addmes'][12]="Сообщение:";
$language['addmes'][13]="Добавить!";
$language['addmes'][14]="Сообщение успешно добавлено!!";

$language['editmes'][0]="Сообщение успешно изменено!!";
$language['editmes'][1]="ПОСМОТРЕТЬ";
$language['editmes'][2]="Дата:";
$language['editmes'][3]="Ник:";
$language['editmes'][4]="E-mail:";
$language['editmes'][5]="URL:";
$language['editmes'][6]="Сообщение:";
$language['editmes'][7]="Изменить!";
$language['editmes'][8]="НАЗАД";

$language['topicedit'][0]="Успешно изменено!";
$language['topicedit'][1]="Редактор темы";
$language['topicedit'][2]="Заголовок темы:";
$language['topicedit'][3]="Ник:";
$language['topicedit'][4]="E-mail:";
$language['topicedit'][5]="Url:";
$language['topicedit'][6]="Права для просмотра:";
$language['topicedit'][7]="Описание:";
$language['topicedit'][8]="Изменить!";
$language['topicedit'][9]="Логины тех, кто может смотреть тему:";
$language['topicedit'][10]="<br><SMALL>Через запятую! пример:'Megaman,nikita'.<br> Оставьте пустым, если не хотите включать эту опцию...</SMALL>";

$language['topicadd'][0]="Тема успешно создана!";
$language['topicadd'][1]="ПОСМОТРЕТЬ";
$language['topicadd'][2]="Тема:";
$language['topicadd'][3]="Ник:";
$language['topicadd'][4]="E-mail:";
$language['topicadd'][5]="URL:";
$language['topicadd'][6]="Права для просмотра:";
$language['topicadd'][7]="Описание темы:";
$language['topicadd'][8]="Добавить!";

$language['profilechange'][0]="Длина пароля должна быть не менее";
$language['profilechange'][1]="Длина ника должна быть не менее";
$language['profilechange'][2]="Длина местоположения должна быть не менее";
$language['profilechange'][3]="Длина e-mail'а должна быть не менее";
$language['profilechange'][4]="Длина URL должна быть не менее";
$language['profilechange'][5]="Длина подписи должна быть не менее";
$language['profilechange'][6]="Длина доп. информации должна быть не менее";
$language['profilechange'][7]="символов";
$language['profilechange'][8]="Изменение данных не может быть продолжено!";
$language['profilechange'][9]="назад";
$language['profilechange'][10]="Данные изменены!";
$language['profilechange'][11]="АВАТАРА ЗАГРУЖЕНА!";
$language['profilechange'][12]="Не удалось скопировать";
$language['profilechange'][13]="Не удалось скопировать";
$language['profilechange'][14]=", это не gif картинка!!!";
$language['profilechange'][15]="Не удалось скопировать";
$language['profilechange'][16]="объём картинки должен быть не больше";
$language['profilechange'][17]="Кб, и размер не более";
$language['profilechange'][18]="пикселей!!!";
$language['profilechange'][19]="Надо указать имя файла!";
$language['profilechange'][20]="АВАТАРА УДАЛЕНА!";
$language['profilechange'][21]="Вы зарегистрированы:";
$language['profilechange'][22]="Сообщений:";
$language['profilechange'][23]="Ваше звание:";
$language['profilechange'][24]="Ваш пол:";
$language['profilechange'][25]="Логин:";
$language['profilechange'][26]="Пароль:";
$language['profilechange'][27]="Никнейм:";
$language['profilechange'][28]="Местоположение:";
$language['profilechange'][29]="E-mail:";
$language['profilechange'][30]="URL:";
$language['profilechange'][31]="Подпись:";
$language['profilechange'][32]="Доп. информация:";
$language['profilechange'][33]="Изменить!";
$language['profilechange'][34]="ЗАКАЧАТЬ АВАТАРУ:";
$language['profilechange'][35]="Закачать!";
$language['profilechange'][36]="Текущая аватара:";
$language['profilechange'][37]="Удалить";


$language['reg'][0]="Логин";
$language['reg'][1]="уже занят... Придумайте себе другой!";
$language['reg'][2]="Регистрация не может быть продолжена!";
$language['reg'][3]="Вы зарегистрированы! Вот ваши регистрационные данные:";
$language['reg'][4]="Пол:";
$language['reg'][5]="Ждём вас на форуме по адресу:";
$language['reg'][6]="Ошибка посылки данных на e-mail";
$language['reg'][7]="Сохраните их, они вам пригодятся!";
$language['reg'][8]="Эти данные высланы вам на e-mail";
$language['reg'][9]="Длина логина должна быть не менее";
$language['reg'][10]="Регистрация на форуме";

$language['showrights'][0]="Ваш уровень доступа:";
$language['showrights'][1]="Вы можете";
$language['showrights'][2]="Вы НЕ можете";
$language['showrights'][3]="просматривать темы и сообщения.";
$language['showrights'][4]="добавлять сообщения в темы.";
$language['showrights'][5]="просматривать информацию о пользователях.";
$language['showrights'][6]="добавлять новые темы.";
$language['showrights'][7]="голосовать в темах.";
$language['showrights'][8]="пользоваться приватом форума.";
$language['showrights'][9]="удалять и редактировать свои сообщения.";
$language['showrights'][10]="добавлять голосования в свои темы.";
$language['showrights'][11]="редактировать и удалять чужие сообщения.";
$language['showrights'][12]="редактировать профили пользователей.";
$language['showrights'][13]="редактировать настройки форума.";

$language['version_1.6'][0]="Директория с файлами закачки";
$language['version_1.6'][1]="Файл с разрешёнными расширениями";
$language['version_1.6'][2]="Файл с описаниями файлов закачки";
$language['version_1.6'][3]="Закачка файлов пользователями";
$language['version_1.6'][4]="Разрешить закачку файлов пользователям?";
$language['version_1.6'][5]="Редактор разрешённых к закачке расширений";
$language['version_1.6'][6]="Редактор разрешённых к закачке расширений";
$language['version_1.6'][7]="Редактор закачанных файлов";
$language['version_1.6'][8]="Удалить";
$language['version_1.6'][9]="Вы действительно хотите удалить файл: ";
$language['version_1.6'][10]="ДА";
$language['version_1.6'][11]="НЕТ";
$language['version_1.6'][12]="Файл успешно удалён!";
$language['version_1.6'][13]="НАЗАД";
$language['version_1.6'][14]="<CENTER><b>Скачивание файлов</b></CENTER>";
$language['version_1.6'][15]="ПОИСК";
$language['version_1.6'][16]="DOWNLOAD";
$language['version_1.6'][17]="нет описания";
$language['version_1.6'][18]="<CENTER><b>Закачать файл:</b></CENTER>";
$language['version_1.6'][19]="Разрешены следующие типы:";
$language['version_1.6'][20]="Максимальный размер загружаемого файла (Кб):";
$language['version_1.6'][21]="Максимальная длина описания файла (символов):";
$language['version_1.6'][23]="Выберите файл:";
$language['version_1.6'][24]="Описание файла:";
$language['version_1.6'][25]="Загрузить!";
$language['version_1.6'][26]="Такой файл уже существует!";
$language['version_1.6'][27]="Максимальная длина названия файла:";
$language['version_1.6'][28]="НАЗАД!";
$language['version_1.6'][29]="ОШИБКА! Нельзя загружать файлы более ";
$language['version_1.6'][31]=" Кб!";
$language['version_1.6'][30]="ОШИБКА! Название файла должно быть не длиннеее ";
$language['version_1.6'][32]="символов!";
$language['version_1.6'][33]="Не удалось загрузить файл!";
$language['version_1.6'][34]="Файл успешно загружен!";
$language['version_1.6'][35]="Нельзя загружать файлы этого формата!";
$language['version_1.6'][36]="Всего записей просмотрено:";
$language['version_1.6'][37]="Искомая комбинация встречается в";
$language['version_1.6'][38]="записях...";
$language['version_1.6'][39]="Тема:";
$language['version_1.6'][40]="посмотреть";
$language['version_1.6'][41]="Комбинация";
$language['version_1.6'][42]="нигде не встречается...";
$language['version_1.6'][43]="Искать ещё";
$language['version_1.6'][44]="Найти";

$language['version_1.61'][0]="Переместить";
$language['version_1.61'][1]="Гость";
$language['version_1.61'][2]="<CENTER><b>Переместить сообщение</b></CENTER>";
$language['version_1.61'][3]="Куда вы хотите переместить это сообщение?";
$language['version_1.61'][4]="В тему:";
$language['version_1.61'][5]="Ник:";
$language['version_1.61'][6]="Сообщение:";
$language['version_1.61'][7]="Дата:";
$language['version_1.61'][8]="Сообщение успешно перемещено!";
$language['version_1.61'][9]="Из темы:";
$language['version_1.61'][10]="Переместить!";
$language['version_1.61'][11]="<br><SMALL>[Перемещено из темы: \"";
$language['version_1.61'][12]="\"]</SMALL>";
$language['version_1.61'][13]="ПОСМОТРЕТЬ";
$language['version_1.61'][14]="Вы уверены, что хотите очистить тему?";
$language['version_1.61'][15]="ТЕМА:";
$language['version_1.61'][16]="ДА";
$language['version_1.61'][17]="НЕТ";
$language['version_1.61'][18]="Тема очищена!";
$language['version_1.61'][19]="НАЗАД";
$language['version_1.61'][20]="Очистить тему";

$language['version_1.7'][0]="РАЗДЕЛЫ";
$language['version_1.7'][1]="<CENTER><b>Список разделов форума</b></CENTER>";
$language['version_1.7'][2]="Модераторы";
$language['version_1.7'][3]="Переместить";
$language['version_1.7'][4]="Укажите в какой раздел переместить тему ";
$language['version_1.7'][5]="В раздел:";
$language['version_1.7'][6]="<CENTER><b>Переместить тему</b></CENTER>";
$language['version_1.7'][7]="Из раздела";
$language['version_1.7'][8]="Тема успешно перемещена!";
$language['version_1.7'][9]="ПОСМОТРЕТЬ";
$language['version_1.7'][10]="Редактор разделов";

$language['version_1.7'][11]="Название";
$language['version_1.7'][12]="Описание";
$language['version_1.7'][13]="Расшир.";
$language['version_1.7'][14]="Права";
$language['version_1.7'][15]="Модераторы";
$language['version_1.7'][16]="Исп.";
$language['version_1.7'][17]="+ РАЗДЕЛ";
$language['version_1.7'][18]="- РАЗДЕЛ";
$language['version_1.7'][19]="Всего сообщений на форуме:";
$language['version_1.7'][20]="Просмотр";
$language['version_1.7'][21]="Название";
$language['version_1.7'][22]="Описание";
$language['version_1.7'][23]="Всего тем";
$language['version_1.7'][24]="Новые";
$language['version_1.7'][25]="Есть новые сообщения с момента вашего последнего входа в раздел.";
$language['version_1.7'][26]="Нет новых сообщений с момента вашего последнего входа в раздел.";

$language['version_2.0'][0]="Всего сообщений на форуме:";
$language['version_2.0'][1]="Вы действительно хотите удалить из темы ";
$language['version_2.0'][2]="страницу";
$language['version_2.0'][3]="Страница удалена успешно!";
$language['version_2.0'][4]="Удалить диапазон";
$language['version_2.0'][5]="Удалить от";
$language['version_2.0'][6]="до";
$language['version_2.0'][7]="УДАЛИТЬ";
$language['version_2.0'][8]="НАЗАД";
$language['version_2.0'][9]="Последнее сообщение";
$language['version_2.0'][10]="Пользователи он-лайн:";
$language['version_2.0'][11]="Просмотр юзеров онлайн";
$language['version_2.0'][12]="тип";
$language['version_2.0'][13]="ник";
$language['version_2.0'][14]="логин";
$language['version_2.0'][15]="время";
$language['version_2.0'][16]="юзер";
$language['version_2.0'][17]="гость";
$language['version_2.0'][18]="№";
$language['version_2.0'][19]="IP - адрес";
$language['version_2.0'][20]=" - - - ";
$language['version_2.0'][21]="на форуме";
$language['version_2.0'][22]="тема";
$language['version_2.0'][23]="список форумов";
$language['version_2.0'][24]="права";
$language['version_2.0'][25]="опрос";
$language['version_2.0'][26]="<b>[закрыта]</b>";
$language['version_2.0'][27]="Закрыть тему";
$language['version_2.0'][28]="Вы действительно хотите закрыть тему ";
$language['version_2.0'][29]="Да, закрыть тему";
$language['version_2.0'][30]="Тема закрыта";
$language['version_2.0'][31]="Открыть тему";
$language['version_2.0'][32]="Вы действительно хотите открыть тему ";
$language['version_2.0'][33]="Да, открыть тему";
$language['version_2.0'][34]="Тема открыта";
$language['version_2.0'][35]="ОБЫЧНАЯ";
$language['version_2.0'][36]="Изменить";
$language['version_2.0'][37]="ЦВЕТОВАЯ СХЕМА:";
$language['version_2.0'][38]="Новички (за неделю):";

$language['version_2.0'][39]="Главные настройки";
$language['version_2.0'][40]="Ранги и доступ";
$language['version_2.0'][41]="Логи и блокировка";
$language['version_2.0'][42]="Технические настройки";
$language['version_2.0'][43]="Download";
$language['version_2.0'][44]="Supervisor";

$language['version_2.0'][45]="Переместить диапазон";
$language['version_2.0'][46]="Сообщения перемещены успешно";
$language['version_2.0'][47]="от";
$language['version_2.0'][48]="до";

$language['version_2.0'][49]="Как связаться с";
$language['version_2.0'][50]="Статус на форуме";
$language['version_2.0'][51]="Дополнительно";
$language['version_2.0'][52]="Аватара:";
$language['version_2.0'][53]="Посмотреть графики активности";
$language['version_2.0'][54]="Показать статистику за N дней:";
$language['version_2.0'][55]="Показать";
$language['version_2.0'][56]="Графики активности форума";
$language['version_2.0'][57]="Цвет оповещения о сообщениях привата";

$language['version_2.0'][58]="Отметить все разделы как прочтённые";
$language['version_2.0'][59]="url";
$language['version_2.0'][60]="цит";
$language['version_2.0'][61]="выводить каждую N-ю подпись";
$language['version_2.0'][62]="Удалить старые аккаунты";
$language['version_2.0'][63]="Удаление старых аккаунтов";
$language['version_2.0'][64]="Удалить тех, чей файл не менялся более ";
$language['version_2.0'][65]="дней";
$language['version_2.0'][66]="Аккаунт удалён: ";
$language['version_2.0'][67]="читать";
$language['version_2.0'][68]="удалить";
$language['version_2.0'][69]="Сообщение №";
?>