<?php
$fp=fopen($file_forum_ini,"w+");
$s="[}={]";
$zapis=$vars['login_len']."$s".$vars['login_min']."$s".$vars['pass_len']."$s".$vars['pass_min']."$s".$vars['nick_len']."$s".$vars['nick_min']."$s".$vars['email_len']."$s".$vars['email_min']."$s".$vars['url_len']."$s".$vars['url_min']."$s".$vars['city_len']."$s".$vars['city_min']."$s".$vars['sign_len']."$s".$vars['sign_min']."$s".$vars['info_len']."$s".$vars['info_min']."$s".$vars['title_len']."$s".$vars['title_min']."$s".$vars['desc_len']."$s".$vars['desc_min']."$s".$vars['mes_len']."$s".$vars['mes_min']."$s".$vars['your_email']."$s".$vars['your_name']."$s".$vars['forum_addr']."$s".$vars['forum_name']."$s".$vars['time_zone']."$s".$vars['kvo']."$s".$vars['time_exit']."$s".$vars['show_users']."$s".$vars['show_online']."$s".$vars['log_index']."$s".$vars['log_auth']."$s".$vars['mat_filter_word']."$s".$usr_view['nick']."$s".$usr_view['avatar']."$s".$usr_view['city']."$s".$usr_view['email']."$s".$usr_view['url']."$s".$usr_view['sex']."$s".$usr_view['sign']."$s".$usr_view['rang']."$s".$usr_view['count']."$s".$usr_view['raiting']."$s".$vars['avatar_maxwidth']."$s".$vars['avatar_maxheight']."$s".$vars['avatar_maxsize']."$s".$vars['theme_ext']."$s".$vars['mess_ext']."$s".$vars['voting_ext']."$s".$levels[0]."$s".$levels[1]."$s".$levels[2]."$s".$levels[3]."$s".$levels[4]."$s".$levels[5]."$s".$levels[6]."$s".$levels[7]."$s".$vars['guest_rights']."$s".$vars['reg_rights']."$s".$smb."$s".$smb1."$s".$table_all."$s".$td_all."$s".$table_messages."$s".$td_messages."$s".$td_userinfo."$s".$vars['show_rights']."$s".$vars['show_statistic']."$s".$vars['show_info_banner']."$s".$vars['__contents']."$s".$vars['show_owner']."$s".$vars['subj_len']."$s".$vars['subj_min']."$s".$vars['pmes_len']."$s".$vars['pmes_min']."$s".$vars['show_newpm']."$s".$vars['t_kvo']."$s".$vars['show_thhp']."$s".$vars['show_view_t']."$s".$vars['make_chmod']."$s".$vars['show_gentime']."$s".$vars['word_len']."$s".$vars['smls_count']."$s".$vars['language']."$s".$vars['downl_enable']."$s".$vars['file_maxsize']."$s".$vars['file_maxdesc']."$s".$vars['file_maxlen']."$s".$vars['mat_filter']."$s".$vars['pers_color'];
fwrite($fp,"$zapis");
fclose($fp);
$fp=fopen($file_directories,"w+");
$zapis="<?php
\$vars['dir_users']=\"".$vars['dir_users']."\";
\$vars['dir_themes']=\"".$vars['dir_themes']."\";
\$vars['dir_voting']=\"".$vars['dir_voting']."\";
\$vars['dir_avatars']=\"".$vars['dir_avatars']."\";
\$vars['dir_smiles']=\"".$vars['dir_smiles']."\";
\$vars['file_online']=\"".$vars['file_online']."\";
\$vars['file_logs']=\"".$vars['file_logs']."\";
\$vars['file_rangs']=\"".$vars['file_rangs']."\";
\$vars['file_auth_logs']=\"".$vars['file_auth_logs']."\";
\$vars['file_blocked_ips']=\"".$vars['file_blocked_ips']."\";
\$vars['file_files_desc']=\"".$vars['file_files_desc']."\";
\$vars['file_files_ext']=\"".$vars['file_files_ext']."\";
\$vars['dir_downloads']=\"".$vars['dir_downloads']."\";
\$vars['file_mat_filter']=\"".$vars['file_mat_filter']."\";

?>
";
fwrite($fp,"$zapis");
fclose($fp);
?>